import type { Metadata } from "next";

import "./globals.css";
import ThemeRegistry from "./theme-provider";
import { Manrope } from 'next/font/google';
import { Toaster } from 'react-hot-toast';


const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: "Next.js",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={manrope.className}>
      <body>
        
        <ThemeRegistry>
        <Toaster position="top-center" reverseOrder={false} />
          {children}
          </ThemeRegistry>
      </body>
    </html>
  );
}
